### ISSUE TITLE
Implement OnyxSelect

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#565] opened 2024-03-11 14:06 UTC
### Depends on

- #564 
- #568 
- #706 
- #762

### Why?

Allow the user to select one or multiple entries from a list of options.

### Design

[Figma](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=1569-34084&mode=design&t=lgLzv7i9PKKCmZad-4)

### Acceptance criteria

- [x] Figma design is implemented 
- [x] label can be shown or hidden (then `aria-label` is used instead)
- [x] All densities are implemented
- [x] Can be set to skeleton mode
- [x] Can be set to loading

**Out-of-scope**

- valid
- invalid

### Definition of Done

- [x] example usage added to alpha-test-app
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- [Storybook link](https://storybook.onyx.schwarz/?path=/docs/components-select--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @BoppLi 

### Implementation details

```typescript
type OnyxSelectProps<TValue> = {
  label: string;
  hideLabel?: boolean;
  skeleton?: boolean;
  loading?: boolean;
  hideSearch?: boolean;
  searchTerm?: string;
  open?: boolean;
  // add searchFunc callback
  modelValue?: ComboboxOption<TValue>;
  options: ComboboxOption<TValue>[];
}

type OnyxSelectEmits<TValue> = {
  (event: "update:modelValue", value: ComboboxOption<TValue>): void;
  (event: "update:searchTerm", value: string): void;
  (event: "update:open", value: boolean): void;
};
```

- The visible placeholder area is not an actual input!
- Make use of `packages/headless/src/composables/comboBox/createComboBox.ts`
- Extend with the listbox implementation in `packages/headless/src/composables/listbox/createListbox.ts`

#### Reference implementations

- [KendoUI](https://www.telerik.com/kendo-vue-ui/components/dropdowns/combobox/)
- [Vuetify](https://vuetifyjs.com/en/components/combobox/)

#### Applicable ARIA Pattern

[Combobox](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/)

**Comment by BoppLi** [comment] 2024-03-25 17:23
Note: using a native input at the core of the select (with readonly mode) actually gives a nice benefit of making a long multi select text scrollable :)

**Comment by larsrickert** [comment] 2024-05-27 10:03
pass missing skeleton and textMode props to OnyxSelectInput

**Comment by BoppLi** [comment] 2024-06-03 09:55
Review findings:

1) [https://storybook.onyx.schwarz/?path=/story/components-select--multiselect](https://storybook.onyx.schwarz/?path=/story/components-select--multiselect&args=searchTerm:) example is wrong. "selected unavailable fruit" should be preselected. compare https://storybook.onyx.schwarz/?path=/story/components-checkboxgroup--with-check-all

2) #706 states:
> Implementation details
> During search "Check All" is hidden
![image](https://github.com/SchwarzIT/onyx/assets/151019977/21eb5bf8-32b1-4b0e-b044-da1f99310b35)

**Comment by larsrickert** [comment] 2024-06-04 08:47
@BoppLi 
3. I don't think so, we would need to define the source code as string I guess
4. The headless composables are named depdnign on their implemented aria pattern (which is combox) but the select is only a combobox if it has the search, without the search its not a combox, thats why we decided to call it "Select"
5. Thats the intended behaviour because the search value should be cleared when closing the flyout
7. Thats the indended behaviour because you can not select with space because space should be typed into the input. I will update the docs that select with space is only working when search is disabled

I will create a PR for the rest

**Comment by BoppLi** [comment] 2024-06-04 12:04
about 5) yes but it emits even when it was empty before. imho events should only emit if the value actually changes?

**Comment by larsrickert** [comment] 2024-06-04 12:07
> about 5) yes but it emits even when it was empty before. imho events should only emit if the value actually changes?

Ah okay now I got it, yes I will fix it

Follow up for 6) is #1234

**Closed** 2024-06-04 12:46 UTC
Labels: dev, wawi
