### ISSUE TITLE
Define (targeted) headlines

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#700] opened 2024-03-20 09:47 UTC
- Regard action item of echometer and discussion #616
- Regard hashtag after/before headlines as a jumpmark 
- Regard https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin-block

**Comment by JoCa96** [comment] 2024-09-16 13:22
Duplicate of [#94](https://github.com/SchwarzIT/onyx/issues/94)

**Closed by JoCa96** 2024-09-16 13:22 UTC
Labels: ux, dev
