### ISSUE TITLE
Implement Invalid behavior

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#617] opened 2024-03-13 12:45 UTC
### Depends on

- #385 

### Why?

This is a follow-up ticket, which will be filled as a result of the predecessor ticket.

### Design

_add Figma link and comments here_

### Acceptance criteria

- _add ticket specific AC, e.g. the expected behavior of a component_

### Definition of Done

- [ ] example usage added to alpha-test-app
- [ ] covered by component tests
- [ ] screenshot tests are updated
- [ ] follow-up tickets were created if necessary
- [ ] updated version + documentation is deployed
- [ ] Storybook can show the feature
- [ ] Set task to `In Approval`

**Review**

- _add link to deployed storybook_
- _add link to deployed docs_
- [ ] approved by designer @jannick-ux
- [ ] approved by dev _add dev tag_

### Implementation details

_add details if necessary, e.g.:_

- _API proposal_
- _relevant web APIs_
- _learnings from other implementations_
- _code snippets_

#### Reference implementations

- _add links to other framework and WaWi_

#### Applicable ARIA Pattern

_add link if applicable_

**Comment by larsrickert** [comment] 2024-04-16 12:43
Duplicate of #385

**Closed by larsrickert** 2024-04-16 12:43 UTC
Labels: dev
