### ISSUE TITLE
Implement OnyxNumberInput

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1273] opened 2024-06-11 08:46 UTC
Depends on 
- #850 

## Implementation details

Add the following validation options back to `packages/sit-onyx/src/composables/useCustomValidity.ts`
```
    min?: number;
    max?: number;
    step?: number;
```

**Comment by BoppLi** [comment] 2024-06-11 08:48
Further Info for Implementation details.
In #570 first we prepared validation options for the number input aswell, but because it was not implemented yet, they were removed.
To get them back, re-add the following code line in useCustomValidity:

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/a04f5eb4-4865-4abf-856b-45adc28340e4)
and

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/affeb366-6624-456c-9535-9564a1b8d905)

**Comment by larsrickert** [comment] 2024-06-19 12:02
Duplicate of #1348

**Closed by larsrickert** 2024-06-19 12:02 UTC
