### ISSUE TITLE
Implement OnyxButton "active" animation

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#362] opened 2024-02-20 09:30 UTC
### Description

Implement OnyxButton "active" animation

### Confirmations

- [x] I have checked that there is not already a feature request for this feature.
- [x] I confirm that are no sensitive information included in this feature request. e.g. credentials, internal project details (for employees of the Schwarz Group) etc.

**Comment by larsrickert** [comment] 2024-08-19 09:26
Duplicate of #363

**Closed by larsrickert** 2024-08-19 09:26 UTC
Labels: dev
