### ISSUE TITLE
Document "Beta" as new version name everywhere

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1246] opened 2024-06-05 09:59 UTC
- [ ] Docs: wherever it is named "we are in alpha", rename it to "beta"
- [ ] Config file for the release artifact: set beta instead of alpha for our npm packages
- [ ] Check what happens with https://onyx.schwarz/development/packages/changelogs/sit-onyx.html

**Comment by JoCa96** [comment] 2024-06-20 13:52
Dupe of #1275

**Closed by JoCa96** 2024-06-20 13:52 UTC
Labels: documentation, dev
